name: CI/CD Pipeline Invoice

on:
  push:
    branches: 
      - main
      - feature/order-invoice

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm test

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - run: echo "🚀 Deploy demo from feature branch"
